version: '2'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3309:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: integrador
      MYSQL_DATABASE: integrador
      MYSQL_USER: root
      MYSQL_PASSWORD: integrador
